{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "Q1. Describe three applications for exception processing.\n",
        "---> Below are the three common applications for exception processing:\n",
        "\n",
        "Error Handling: Exception processing is widely used for error handling in software development. When an error or exceptional condition occurs during the execution of code, an exception can be raised, indicating that something unexpected or erroneous has happened. By using exception handling constructs, such as try-catch blocks, you can catch and handle these exceptions gracefully. Error handling allows you to provide fallback strategies, display meaningful error messages, log errors, or take appropriate actions to recover from the error state.\n",
        "\n",
        "Input Validation: Exception processing is often employed for input validation and handling invalid or unexpected input. When validating user input or processing external data, exceptions can be raised when the input does not conform to expected formats or constraints. For example, if you expect a numeric input but receive a string, an exception can be raised to indicate the invalid input. By catching and handling these exceptions, you can prompt the user to provide valid input or take alternative actions.\n",
        "\n",
        "Resource Management: Exception processing is crucial for managing resources, such as files, network connections, or database connections. When working with external resources, exceptions can occur if there are issues with opening, reading, writing, or closing the resources. Exception handling allows you to ensure that resources are properly released and cleaned up, even in the presence of errors. For example, when reading data from a file, if an exception occurs during the process, you can catch the exception and close the file handle to release system resources."
      ],
      "metadata": {
        "id": "d_qlikPdET5P"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q2. What happens if you don't do something extra to treat an exception?\n",
        "---> If an exception is not handled or caught in your code, it will propagate up the call stack until it reaches the nearest exception handler or until it reaches the top level of your program. If the exception reaches the top level without being caught, it will typically result in the termination of your program, and an error message or traceback will be displayed."
      ],
      "metadata": {
        "id": "Ou8uudi1Ekan"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q3. What are your options for recovering from an exception in your script?\n",
        "---> When an exception occurs in your script, you have several options for recovering from it and continuing the execution of your program. The specific approach to recovery depends on the nature of the exception and the desired behavior of your script. Here are some common options for recovering from an exception:\n",
        "1. Catch and Handle the Exception\n",
        "2. Retry Mechanism\n",
        "3. Exception Logging and Termination"
      ],
      "metadata": {
        "id": "rbpxLut5EwgL"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q4. Describe two methods for triggering exceptions in your script.\n",
        "---> There are several ways to trigger exceptions in your script, depending on the programming language you are using. Here, I'll describe two common methods for triggering exceptions in Python:\n",
        "\n",
        "1. Using the raise Statement: You can explicitly raise an exception using the raise statement. This allows you to generate and throw exceptions at specific points in your code when certain conditions are met. The raise statement is followed by an exception object or class, which represents the type of exception to be raised.\n",
        "2. Built-in Exceptions: Python provides a wide range of built-in exceptions that can be triggered under different circumstances. These exceptions are predefined classes that represent common error conditions. You can raise these exceptions directly or by calling certain functions or methods that are designed to raise specific exceptions."
      ],
      "metadata": {
        "id": "b6mpcdurFJUb"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q5. Identify two methods for specifying actions to be executed at termination time, regardless of whether or not an exception exists.\n",
        "---> There are two methods in Python for specifying actions to be executed at termination time, regardless of whether or not an exception exists. These methods are using the finally clause and utilizing context managers.\n",
        "\n",
        "1. finally Clause:\n",
        "The finally clause is used in conjunction with try and except blocks to define a set of statements that will be executed regardless of whether an exception is raised or not. The code within the finally block is executed after the try block and any associated except blocks, ensuring that the specified actions are performed even if an exception occurs.\n",
        "2. Context Managers:\n",
        "Context managers provide a more structured and reusable approach for specifying actions to be executed at termination time. Context managers are created using the with statement and can define a setup operation to be executed before a block of code and a cleanup operation to be executed after the block, regardless of exceptions."
      ],
      "metadata": {
        "id": "Tbo7rwqIFZHo"
      }
    }
  ]
}